logging:
  level: INFO
  loggers:
    com.hilton.demo: INFO

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: password
  url: jdbc:postgresql://localhost:5432/GeoLocator
  # mem:sample

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create
    hibernate.show_sql: true

